node_js:
  - '0.10'

sudo: false
language: javascript
cache: bundler

branches:
  only:
    - master

env:
  global:
    - secure: QHKaYCq1MSyliHVxjZdwEYfnV4rDIxcyDu6aVU/VMMmQ/dU7xPtcJUrCMSBXte07lbnXe1CcyWMvzsKfwut1vpmqGqSD84UjBpeFaeS+Qhb13V7ogkbzxyJlw/zuSVS00W2rITptXIK9kNjRfL7S5EqtJ7EQGWrx72vXmEUpIYqD2MzmsJ5Eae3s0QR0xnwV/MM/nlS36XE2ZZMCs27X1EWM1+tCtMaiUlJmxiiVPabG7vlPWkku3TMfwh5Q9P+M5Ec/Jb/qNu+YzUJmSg9Ce1Qr1NNOOX1KuRX9C2lr7WTzclql3CGKT2pi/fEv5C2dI2dWLyA1Tda0TvxJpO39bMCS1fP7zS5pyeQoCbdGXFHFQ1jknrpCbE79BUgwBQeYtOkUVyE0BFID820qBNX/X40aD96LqGEX1IAWOk25+ZzJohMehOPUWIfOneGWzeqcSvHvvpGMkI2T+e0V7JAOr1DO7olXyQUqYg/hP5YbnzAjE+8GHN3p9I2qsI6rEP/+QcKigJ+Qp7AsD0l5azWFLZfSuUsv+PbBYcoXXEYYB61CINnh1QjL4uQ/0dub5SA+Vjfmq3eeJkvsg9gi4dKi7Ux7YjzHg49tVpAUTPtZ0iO55czUZpynnUhR1oLFuWdLE07ReUaC3VByRMk38gUA0N+Q4e8dOYMgr0wLByXKK+I=
    - secure: byBxjTmQU+xTu4SUreQ9Z46tWTM9+OhHGX1IQDOt3RyPydDpBUOIG4jyT24Nw9lOTxeXEAAuKxd8OMaLPfbGugpRV9zhjNe1kN9cbkPo/F8y5FayWyC7gqzepQSgM7Wx2wLu7cczfO7DTfFyLrMFWqFjTh0eHIq5AW5Kp0zKFA50j1C6C0sbwefAetQ17kwb4bzXWm/FkptukVWprB8pYck8Rnvup37JPGwoPaVwlK4ievX9vjzeFQmMg6OTUbtuHoKPYtNy3p3yEG8loYUMW40umbYe1zzLsB+CLgQ+GyQFBzAj429U+byW5/Uk+Dts5sqSDj9aczKJu7u3QbKwCEyzKz5Br0h3mb0b5Ch21CgyfcGRi8e4k3PxEht/46PeES+eUEP/0sWUG3SkanquoNOKf/reus1oFfHO6oV9Lebkw4BXWfQw1Dy4+04CtG+yWXy5ncN8AcmA7yhpGVAWzdyWBM31bldGuvkJwWnj0Xz7gEVeg0798Z+xiVANJ0oMUMzaFfR7BMCZpDnctKHN3qnpQkkc8WIc4mNIZn9vzXQe8RPuUIxFDjTeJmJCZsmI7/IZr+jjEMddLOwzV+Vc65UDycp/hUnuuzQuUPhwWQBVt9bDQDq6G3t3DiBMEJSbWdqBbZIRDA00ymL2OyzW5b7Q4gkuVgCa/nA6iI8ga3I=

before_install:
  - sudo apt-get install -y graphicsmagick
  - npm install

script: "npm run regression && gulp unit-test"

after_script:
  - CODECLIMATE_REPO_TOKEN=62a8b57fa1d855268b67ef956de0991851778758e6036b0981fd956d913f715f codeclimate-test-reporter < reports/coverage/lcov.info
