node_js:
  - '0.10'

branches:
  only:
    - master

addons:
  code_climate:
    repo_token: 62a8b57fa1d855268b67ef956de0991851778758e6036b0981fd956d913f715f

before_install:
  - sudo apt-get install -y graphicsmagick
  - npm install

script: "npm run regression && unit-test"

after_script:
  - cat reports/coverage/lcov.info | codeclimate; fi
