node_js:
  - '0.10'

branches:
  only:
    - master

env:
  global:
    - secure: W/EUgeyZypm8njC9mfr3a60ncloOD3VD9OLFeft++HUiPydL8SyzKPk6XCV5SwBzToVD2N/2YloQQMITkiwBBv60dfvIQ+CYANKGaFzJVbkedxEs8CKnbE2YfRhzirkcDVMOTBhNMaof3oUXOh1iprMtbswtA4IRWK1eq2qG3bPQGBPtzx+bGe3vYihi3MYoiyIQi94kfyZlkkuI7futs6NWGYYz5zpO7KwNLD0yX5DUGgYVRzkIbXYtPFqp45nPCGkNlIxYwWHj5dj94y3lxGOt0YVPlAOZt0aKXW9udbA2WYlOkSDhMFzdDqWKbB/YYsTujq/193eb3a/y1lDM8xhgQFgbd8HbmZnxDPTFUEE5VXvFy7CKVnR5Y1rX47r4GWDY7vuvEQYkFHM/RLW+dZuMVsDm+tUJLNfV0/cg3jQE53t0DSPADXiN30cgN8D8eAWmRbpUR6PBYt6xzhkpC9tGivJ26SXOAytsjkhBuB7aXv5sw4tNmuB46J5LAq85RlGieXV0TGKS6FEDUceX/8Ct++0eCmnwytgLgLesIdpN0C6zHc0tR0t4n4kbhSCkijPWIFXCA+CtxkHNMCDDWmbrdwN6bOvMGgAA7aSTQ7TQjCFZpkjeXvxAEcpB3FkRsznGP9ckYMvqX3ewrPWx1yNIKnn3EQxp1x2WyGvhHaQ=
    - secure: lx9EP+onLkUsu1IivLwe4j9C/kCSjLko9yws233s4GofosKY5+zFYWUMXFqJCGbMOwEq45OTxNMDPFo3asxivKrLWZTDYCIXC69saRAf1u5kW26lmJ+9mBNaSDgtMFbUvyvXWQ5/co7Sf1Uk+ckDjsPZ9iv3dlCM6/XZY4mu9E29j3TiUsDsy77Wh6n3IIbN+Wq9G2/q6OMIAqb+thF4AMClUPG44iYze/gyPtFNEGFzcH6bC/dsdbm31lqMEmPxpomX5mv+HscwQ0v25nNzO4cwDGouif4ouhnpgCLjeSWZeZddaRxPlD/BtPJTAslTVwQ0d7uBZqtRsNoIxfvMpssiCr27fz4JFpYYzw3vbBOrRbU2nv73sr8+/i2+NZEHUt4xWf0vCZglHFll+klPBCRj8Hi0sn9O834sRFUs0J1A6vlczpqgcIsH0PSgxisejTyT18YumGsTUNN99YUwfUBOSmhRUulUXMKFdweJFsd4Fq5Kj4el+3Zsra21NgVDgDZeMzTq8alN40cDtBxFsh7oJ7KHMK4Cq89KZTvxWwFhqf+sVY96VHdiQsiKLRVTOUnAQ5UIfIQlcI2P/nRwOWOu9gyyneQRb2ioPEC2gzGEgiK4OW3jqsSoVtCwSOESKOK/yzwwwlFuTMNJjB/WLEXRT78pQBxq9Bfh6PTu9+8=

addons:
  sauce_connect: true

before_install:
  - sudo apt-get install -y graphicsmagick
  - npm install

script: "npm run regression && gulp unit-test"

after_script:
  - CODECLIMATE_REPO_TOKEN=62a8b57fa1d855268b67ef956de0991851778758e6036b0981fd956d913f715f codeclimate-test-reporter < reports/coverage/lcov.info
